name: 🐛 Bug Report
description: Report a bug or issue with the platform
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: dropdown
    id: user-role
    attributes:
      label: User Role
      description: What role were you using when the bug occurred?
      options:
        - Super Admin
        - Org Admin
        - Contractor
        - User
        - Not logged in
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 120, Safari 17, Firefox 121
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: e.g., macOS 14, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
